apiVersion: apps/v1
kind: Deployment
metadata:
   name: length
   labels:
      app: length
spec:
   replicas: 1
   selector:
      matchLabels:
         app: length
   template:
      metadata:
         labels:
            app: length
      spec:
         containers:
            - name: length
              image: gstogiannis.azurecr.io/gstogiannis/length:latest
