name: AKS Cluster deployment

on: [push]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - uses: Azure/docker-login@v1
           with:
              login-server: gstogiannis.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

         - uses: azure/setup-kubectl@v4

         - uses: Azure/k8s-set-context@v4
           with:
              kubeconfig: ${{ secrets.KUBE_CONFIG }}

         - uses: Azure/k8s-deploy@v4
           with:
              action: deploy
              manifests: |
                 manifests/deployment.yml
              images: |
                  nginx:1.17.3
              imagepullsecrets: |
                 demo-k8s-secret
